improve functionality

diff --git a/mew b/mew
--- a/mew
+++ b/mew
@@ -31,6 +31,30 @@ case "$choice" in
 	;;
 esac
 
+printf "Creating your folder for your resume or having an existing folder already? \n\n
+\t 1) Create files for specific folder\n\n
+\t 2) Don't create any folder, use current folder\n\n"
+read -rp "Choose your option: 1,2,3 or q to quit: " choice
+case "$choice" in
+    1) read -rp "Go to folder: " folder
+       if [[ ! -d "$folder" ]] && [[ ! -z "$folder" ]]; then 
+	   echo "Folder not Found, creating new folder $folder "
+	   mkdir $folder
+       elif [[ -z "$folder" ]]; then
+	   echo "Empty folder name, please try again "
+	   mew
+	   exit 1
+       fi
+	   folderFlag=true
+       ;;
+    q)
+	exit 1
+	;;
+    *)
+	folderFlag=false
+	;;
+esac
+
 # Get Job number
 read -rp "Job number: " jobNum
 
